<?php
function storleden_module_theme($existing, $type, $theme, $path) {
  return array(
	  	'text_slider' => array(
	            			'variables' => array(	                		
	                						  'nodesArray' => 'slides'
	            							),
	        			),
	    'latest_projects' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'tjanster' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'products_angular' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes',
	    										  'cats' => 'defalt'
	    										)
	    					),
	    'screen_image_text' => array(
	    						'variables' => array(
	    										  'node' => 'node'
	    										)
	    					),
						    						    					
	    'test' => array(
	    						'variables' => array(
	    										  'node' => 'node'
	    										)
	    					),
	    'our_products_slider' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'kontakt_for_test' => array(
	    						'variables' => array(
	    										  'form' => 'form'
	    										)
	    					),
	    'kontakt' => array(
	    						'variables' => array(
	    										  'form' => 'default value'
	    										)
	    					),
	    'person' => array( //name of twig file
	        'variables' => array( // key word
	          'ingress'	=> 'hook ingress',
	          'getPerson' => 'Okänt getPerson'  ,
	        ),
	      ),	    						    				
     'references' => array( //name of twig file
        'variables' => array( // key word
          'picture'   => 'Bild saknas' ,
        				),
      			),
     'linkbutton' => array( //name of twig file
        'variables' => array( // key word
          'sendMethod' => 'get',
          'url' => '',
          'buttonName' => 'Default name',
        ),
      ),
            				      		    						
    );
}

function storleden_module_template_preprocess_default_variables_alter(&$variables) {
  $variables['title_arrow'] ='/' . drupal_get_path('module', 'storleden_module') . '/images/icon/heading-arrow.png';
}
